kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry:
      from_secret: REGISTRY
    repo: registry.horten.kommune.no/${DRONE_REPO_NAME}
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
      - latest
      - '1.0.0'
      - '1.0'
      - '1'
  when:
    event:
    - push
    
- name: teams-webhook
  image: jdamata/drone-teams
  settings:
    webhook: 
      from_secret: WEBHOOK
  when: 
    status: 
    - success
    - failure

trigger:
  event:
  - push
  - cron