version: '3'
services: 
  thinclients-node:
    build: .
    networks: 
      - dbnet
      - web
    depends_on: 
      - mongodb
    ports: 
      - 3000:3000

  mongodb:
    image: docker.io/library/mongo:latest
    networks: 
      - dbnet

networks: 
  dbnet: 
    internal: true
  web:
